
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_jpa?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #显示true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置创建表的引擎为InnoDB

  thymeleaf:
    cache: false
server:
  port: 1234
  servlet:
    context-path: /
